# ============================================================================
# ZITADEL Init Steps - Entwicklungsumgebung
# ============================================================================
# Konfiguriert die erste ZITADEL-Instanz beim Start
#
# Admin Console: http://localhost:8080/ui/console
# Login: zitadel-admin / Password1!
# ============================================================================

ExternalSecure: false
ExternalDomain: localhost
ExternalPort: 8080

# Erlaube Zugriff über verschiedene Hostnamen (localhost UND zitadel für Docker-intern)
SystemDefaults:
  Multitenance:
    DomainVerificationRequired: false

Database:
  postgres:
    Host: zitadel-db
    Port: 5432
    Database: zitadel
    User:
      Username: zitadel
      Password: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: zitadel
      Password: zitadel
      SSL:
        Mode: disable
      ExistingDatabase: zitadel

# ─────────────────────────────────────────────────────────────────────────────
# Passwort-Policy für Entwicklung lockern
# ─────────────────────────────────────────────────────────────────────────────
DefaultInstance:
  PasswordComplexityPolicy:
    MinLength: 4
    HasUppercase: false
    HasLowercase: false
    HasNumber: false
    HasSymbol: false
  LoginPolicy:
    PasswordCheckLifetime: 87600h
    ExternalLoginCheckLifetime: 87600h
    MfaInitSkipLifetime: 87600h
    SecondFactorCheckLifetime: 87600h
    MultiFactorCheckLifetime: 87600h
    ForceMFA: false
  SecretGenerators:
    PasswordSaltCost: 1

# ─────────────────────────────────────────────────────────────────────────────
# Erste Instanz mit Admin, Service Account und Test-User
# ─────────────────────────────────────────────────────────────────────────────
FirstInstance:
  InstanceName: Godstack Dev
  DefaultLanguage: de
  Org:
    Name: Godstack
    
    # Admin User (für Console Login)
    Human:
      UserName: zitadel-admin
      FirstName: ZITADEL
      LastName: Admin
      Email:
        Address: zitadel-admin@localhost
        Verified: true
      Password: Password1!
      PasswordChangeRequired: false
    
    # Service Account für automatisches Setup via API
    Machine:
      Machine:
        UserName: setup-sa
        Name: Setup Service Account
      MachineKey:
        Type: 1
        ExpirationDate: "2099-01-01T00:00:00Z"
      PAT:
        ExpirationDate: "2099-01-01T00:00:00Z"
  
  # PAT wird hier geschrieben (für automatisches Setup)
  PatPath: /machinekey/pat.txt
  
  # Test User für Entwicklung
  SecondHuman:
    UserName: admin
    FirstName: Test
    LastName: Admin
    Email:
      Address: admin@localhost
      Verified: true
    Password: admin
    PasswordChangeRequired: false
